#!/usr/bin/env bash
set -e
REPOS='hydrogen applicative-parsec helium'

if [ -d build ]; then
  rm -rf build
fi
mkdir build
cd build
cabal sandbox init

for repo in $REPOS; do
  git clone \
    --depth 1 \
    --single-branch \
    --branch master \
    "${HOME}/Projects/${repo}" \
    "${repo}"
  cabal sandbox add-source "$repo"
done

pkgs=""
for repo in $REPOS; do
  pkg="$(basename "$(find "$repo" -maxdepth 1 -type f -name '*.cabal')" .cabal)"
  pkgs="${pkgs} ${pkg}"
done

cabal install -j $pkgs standalone-haddock

pdb="$(find .cabal-sandbox -maxdepth 1 -type d -name '*-packages.conf.d')"
tool="$(cabal exec which standalone-haddock)"
exec "$tool" \
  --package-db="../${pdb}" \
  --hyperlink-source \
  -o html \
  ${REPOS}
